In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [19]:
import numpy as np
import pandas as pd

In [25]:
# two matrics
array1 = np.array([[1, 8, 3],[3, 1, 5]])
array2 = np.array([[3,-2],[8, 4],[8, -8]])
print(array1)
print(array2)

[[1 8 3]
 [3 1 5]]
[[ 3 -2]
 [ 8  4]
 [ 8 -8]]


In [26]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.61449553 0.88925024 0.58531225 0.47750882]
 [0.10612463 0.25266836 0.45798266 0.57877131]
 [0.89486094 0.13343396 0.55084127 0.0760385 ]]


In [27]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 91   6]
 [ 57 -42]]


In [29]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[91, 6], [57, -42]]


In [30]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

3.5


In [31]:
main_data = pd.read_csv("/content/drive/MyDrive/SEM_7_ML/L1/mtcars.csv")

In [32]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
